#ifndef _homies_menu_id_h
#define _homies_menu_id_h

#define MID_MAINMENU			1
#define MID_MAINMENU_PLAY		11
#define MID_MAINMENU_OPTIONS	12
#define MID_MAINMENU_HISCORE	13
#define MID_MAINMENU_EXIT		14
#define MID_MAINMENU_RGTBTN		15
#define MID_MAINMENU_LFTBTN		16
#define MID_MAINMENU_TXTBOX		17
#define MID_MAINMENU_EDITOR		18

#define MID_LOSE				2
#define MID_LOSE_CONTINUE		21
#define MID_LOSE_WUSSOUT		22

#define MID_GOTHISCORE			3
#define MID_GOTHISCORE_ELINE	31
#define MID_GOTHISCORE_OK		32

#define MID_TOPTEN				4
#define MID_TOPTEN_OK			41

#define MID_WINALL				5
#define MID_WINALL_OK			51

#define MID_EDITOR				6
#define MID_EDITOR_LFTBTN		61
#define MID_EDITOR_RGTBTN		62
#define MID_EDITOR_TXTBOX		63
#define MID_EDITOR_EDIT			64
#define MID_EDITOR_DELETE		65
#define MID_EDITOR_ADD			66
#define MID_EDITOR_CANCEL		67

#define MID_EDITNEW				7
#define MID_EDITNEW_TXTLVL		71
#define MID_EDITNEW_ELINE		72
#define MID_EDITNEW_TXTSIZE		73
#define MID_EDITNEW_UPWIDTH		74
#define MID_EDITNEW_DNWIDTH		75
#define MID_EDITNEW_UPHEIGHT	76
#define MID_EDITNEW_DNHEIGHT	77
#define MID_EDITNEW_TXTWIDTH	78
#define MID_EDITNEW_TXTHEIGHT	79
#define MID_EDITNEW_OK			710
#define MID_EDITNEW_CANCEL		711

#define MID_EDITMAP				8
#define MID_EDITMAP_SAVE		81
#define MID_EDITMAP_EXIT		82
#define MID_EDITMAP_TXTTTYPE	83
#define MID_EDITMAP_LFTTTYPE	84
#define MID_EDITMAP_RGTTTYPE	85
#define MID_EDITMAP_TXTTYPEDESC 86
#define MID_EDITMAP_TXTTGFX		87
#define MID_EDITMAP_LFTTGFX		88
#define MID_EDITMAP_RGTTGFX		89
#define MID_EDITMAP_TXTTCLR		810
#define MID_EDITMAP_LFTTCLR		811
#define MID_EDITMAP_RGTTCLR		812
#define MID_EDITMAP_TXTTCLRTYP	813
#define MID_EDITMAP_TXTHOMIE	814
#define MID_EDITMAP_LFTHOMIE	815
#define MID_EDITMAP_RGTHOMIE	816
#define MID_EDITMAP_TXTHOMIETYP 817
#define MID_EDITMAP_TXTTIME		818
#define MID_EDITMAP_ELINETIME	819


#endif